import {test,expect} from '@playwright/test';
import fs from 'node:fs';
fs.mkdirSync('.backup',{recursive:true});
test('3D, hover, keyboard, languages and the fall simulation',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const failed=[];page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
  await page.goto('/');
  await expect(page.locator('#anatomyModel')).toHaveAttribute('data-loaded','true');
  await expect(page.locator('#modelStage')).toHaveAttribute('data-state','assembled');
  await page.screenshot({path:'.backup/desktop-final.png'});
  await page.locator('#modelStage').scrollIntoViewIfNeeded();
  await expect(page.locator('#modelStage')).toHaveCSS('transform','none');
  await page.mouse.move(0,0);
  await expect(page.locator('#modelStage')).toHaveAttribute('data-progress','0.000');
  await expect(page.locator('.product-word,.product-orbit')).toHaveCount(0);
  await expect(page.locator('.brand-logo').first()).toHaveAttribute('src',/vivo-logo/);
  await expect(page.locator('#modelStage')).toHaveCSS('border-top-width','0px');
  await expect(page.locator('#modelStage')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
  const canvas=await page.locator('#anatomyModel').boundingBox();
  await page.mouse.move(canvas.x+15,canvas.y+15);
  await expect(page.locator('#modelStage')).toHaveAttribute('data-state','assembled');
  await expect(page.locator('#explodeBtn')).toBeHidden();
  await page.mouse.move(canvas.x+canvas.width*.27,canvas.y+canvas.height/2);
  await expect(page.locator('#modelStage')).toHaveAttribute('data-progress','1.000',{timeout:10000});
  await expect(page.locator('.model-label')).toHaveCount(8);
  const labelPositions=await page.locator('.model-label').evaluateAll(labels=>labels.map(label=>label.getBoundingClientRect().x));
  expect(Math.max(...labelPositions)-Math.min(...labelPositions)).toBeLessThan(1);
  expect(Math.min(...labelPositions)).toBeGreaterThan(canvas.x+canvas.width*.5);
  await page.screenshot({path:'.backup/exploded-final.png'});
  await page.mouse.move(canvas.x+15,canvas.y+15);
  await expect(page.locator('#modelStage')).toHaveAttribute('data-state','assembled');
  await page.mouse.move(0,0);
  await expect(page.locator('#modelStage')).toHaveAttribute('data-progress','0.000',{timeout:10000});
  await page.locator('#anatomyModel').focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('#explodeBtn')).toHaveAttribute('aria-pressed','true');
  await page.keyboard.press('Escape');
  await expect(page.locator('#explodeBtn')).toHaveAttribute('aria-pressed','false');
  await page.locator('[data-lang=en]').click();
  await expect(page.locator('html')).toHaveAttribute('lang','en');
  await expect(page.locator('#modelState')).toHaveText('Assembled');
  await expect(page.locator('.model-label').last()).toContainText('Protective glass');
  await page.locator('#themeBtn').click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await expect(page.locator('nav .brand-logo')).toHaveCSS('mix-blend-mode','screen');
  await expect(page.locator('nav .brand-logo')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
  await page.locator('#top').scrollIntoViewIfNeeded();
  await page.screenshot({path:'.backup/dark-logo.png'});
  await page.locator('#demo').scrollIntoViewIfNeeded();
  await page.locator('.tab[data-s=off]').click();
  await expect(page.locator('#screen h4')).toHaveText('Unreachable');
  await page.locator('.tab[data-s=off]').press('ArrowDown');
  await expect(page.locator('#screen h4')).toHaveText('All good');
  await page.locator('#simulate').click();
  await expect(page.locator('#count')).toHaveClass('count show');
  await page.locator('#cancel').click();
  await expect(page.locator('#count')).toHaveClass('count');
  await page.locator('#simulate').click();
  await expect(page.locator('#screen h4')).toHaveText('FALL DETECTED',{timeout:13000});
  await page.locator('[data-lang=it]').click();
  await expect(page.locator('#screen h4')).toHaveText('CADUTA RILEVATA');
  await page.screenshot({path:'.backup/demo-dark.png'});
  expect(errors).toEqual([]);expect(failed).toEqual([]);
});

test('phone layout, touch control and reduced motion',async({browser})=>{
  const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
  const page=await context.newPage();await page.goto('http://127.0.0.1:5173');
  await expect(page.locator('#anatomyModel')).toHaveAttribute('data-loaded','true');
  await page.screenshot({path:'.backup/mobile-hero.png'});
  await page.locator('.menu-toggle').tap();
  await expect(page.locator('#navLinks')).toBeVisible();
  await page.locator('#navLinks a[href="#anatomia"]').tap();
  await expect(page.locator('.menu-toggle')).toHaveAttribute('aria-expanded','false');
  await expect(page.locator('#modelStage')).toHaveAttribute('data-state','assembled');
  await expect(page.locator('#explodeBtn')).toBeVisible();
  await page.locator('#explodeBtn').tap();
  await expect(page.locator('#modelStage')).toHaveAttribute('data-progress','1.000');
  await page.locator('#modelStage').scrollIntoViewIfNeeded();
  await page.screenshot({path:'.backup/mobile-exploded.png'});
  await page.locator('#explodeBtn').tap();
  await expect(page.locator('#modelStage')).toHaveAttribute('data-progress','0.000');
  const widths=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
  expect(widths.scroll).toBeLessThanOrEqual(widths.width);
  await page.locator('#demo').scrollIntoViewIfNeeded();
  await page.screenshot({path:'.backup/mobile-demo.png'});
  for(const size of [320,768,1024]) {
    await page.setViewportSize({width:size,height:900});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  }
  await context.close();
});

test('all original editorial content is preserved',async({page})=>{
  await page.goto('/');
  const expected=JSON.parse(fs.readFileSync('tests/original-content.json','utf8'));
  for(const {key,text} of expected) if(key) await expect(page.locator(`[data-t="${key}"]`).first()).toHaveText(text);
});
